# Generated by Django 5.0 on 2024-05-30 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResponsabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('carnet', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='area_responsabilidad',
            name='centro_pertenece',
        ),
        migrations.RenameField(
            model_name='edificio',
            old_name='id_edificio',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='id_local',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reservacion',
            old_name='id_reservacion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sede',
            old_name='id_sede',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nivel_local',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='tiempo_reserv',
        ),
        migrations.AddField(
            model_name='edificio',
            name='subnivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='alto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ancho',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='largo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='local_pertenece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.local'),
        ),
        migrations.AddField(
            model_name='local',
            name='nivel_pertenece',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='final_reserva',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='inicio_reserva',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edificio',
            name='niveles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='area_responsab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.arearesponsabilidad'),
        ),
        migrations.AddField(
            model_name='arearesponsabilidad',
            name='centro_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.centrocosto'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='responsable_centro',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='backend.responsable'),
        ),
        migrations.AddField(
            model_name='arearesponsabilidad',
            name='responsable_area',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='backend.responsable'),
        ),
        migrations.DeleteModel(
            name='Centro_Costo',
        ),
        migrations.DeleteModel(
            name='Area_Responsabilidad',
        ),
    ]
