# Generated by Django 5.0.6 on 2024-06-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_arearesponsabilidad_centrocosto_responsable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edificio",
            name="sede_pertenece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edificios",
                to="backend.sede",
            ),
        ),
        migrations.AlterField(
            model_name="local",
            name="edificio_pertenece",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locales",
                to="backend.edificio",
            ),
        ),
    ]
