# Generated by Django 5.0.6 on 2024-06-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="local_pertenece",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sublocales",
                to="backend.local",
            ),
        ),
    ]
