# Generated by Django 5.0.6 on 2024-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_alter_local_local_pertenece"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local", name="ancho", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="local", name="largo", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
