# Generated by Django 5.0.6 on 2024-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_criterioconstructivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="alto",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="ancho",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="largo",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
