# Generated by Django 5.0.6 on 2024-06-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_local_alto_alter_local_ancho_alter_local_largo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evaluacion", unique_together={("local", "criterio", "fecha")},
        ),
    ]
