# Generated by Django 5.0.6 on 2024-06-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_alter_evaluacion_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluacion", options={"verbose_name_plural": "Evaluaciones"},
        ),
    ]
