# Generated by Django 5.0.6 on 2024-06-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_evaluacion_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="nota",
            field=models.CharField(
                choices=[("B", "Bien"), ("R", "Regular"), ("M", "Mal")],
                default="R",
                max_length=1,
            ),
        ),
    ]
