# Generated by Django 5.0.6 on 2024-06-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_alter_arearesponsabilidad_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criterioconstructivo",
            options={"verbose_name_plural": "Criterios Constructivos"},
        ),
    ]
